# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class QuantizationDetails(object):
    NONE = 0
    CustomQuantization = 1


def QuantizationDetailsCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == QuantizationDetails().CustomQuantization:
        import tflite_model.CustomQuantization
        return tflite_model.CustomQuantization.CustomQuantizationT.InitFromBuf(table.Bytes, table.Pos)
    return None
